### ISSUE TITLE
Opening new sources/deleting existing ones

### ISSUE THREAD

**Issue by martinschorb** [tischi/bdv-utils#11]
Hi,

When I run SpimDataset > Open XML/HDF5 files it always add these to the existing sources list.
This is a bit annoying if I want to look at two different experiments at the same time. I have to do a full Fiji restart to get rid of the previous sources.  When I try to delete all of them to get an empty sources list I get the following crash:

```[ERROR] Module threw exception
java.lang.IllegalArgumentException: node does not have a parent.
	at javax.swing.tree.DefaultTreeModel.removeNodeFromParent(DefaultTreeModel.java:254)
	at sc.fiji.bdvpg.scijava.services.ui.BdvSourceServiceUI.lambda$updateSpimDataFilterNodes$10(BdvSourceServiceUI.java:329)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at sc.fiji.bdvpg.scijava.services.ui.BdvSourceServiceUI.updateSpimDataFilterNodes(BdvSourceServiceUI.java:327)
	at sc.fiji.bdvpg.scijava.services.ui.BdvSourceServiceUI.remove(BdvSourceServiceUI.java:418)
	at sc.fiji.bdvpg.scijava.services.BdvSourceAndConverterService.remove(BdvSourceAndConverterService.java:162)
	at sc.fiji.bdvpg.scijava.command.source.SourcesRemoverCommand.run(SourcesRemoverCommand.java:23)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:228)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

killing the whole BDV and requiring a Fiji restart.

**Comment by martinschorb** [comment]
wrong repo
