### ISSUE TITLE
subsequent saves (ctrl+E) after the registration in BDV raise error

### ISSUE THREAD

**Issue by maximka48** [tischi/bdv-utils#5]
I open one Platynereis dataset (Platy_88_01.h5) in BDV/open multiple xml
I make the registration pressing the 'r' button. Registration completes.
I save the result to tiff with pressing 'ctrl+E' ,  it saves succesfully:
I try to do it again with pressing 'ctrl+E', it fails with:
'''
Exception in thread "Thread-13" java.lang.IllegalArgumentException: invalid range properties
	at javax.swing.DefaultBoundedRangeModel.<init>(DefaultBoundedRangeModel.java:102)
	at javax.swing.JSlider.<init>(JSlider.java:274)
	at bdv.tools.brightness.SliderPanelDouble.<init>(SliderPanelDouble.java:99)
	at bdv.tools.boundingbox.RealBoxSelectionPanel.<init>(RealBoxSelectionPanel.java:115)
	at bdv.tools.boundingbox.TransformedRealBoxSelectionDialog.<init>(TransformedRealBoxSelectionDialog.java:118)
	at bdv.util.BdvFunctions.selectRealBox(BdvFunctions.java:353)
	at de.embl.cba.bdv.utils.BdvDialogs.showBoundingBoxDialog(BdvDialogs.java:612)
	at de.embl.cba.bdv.utils.behaviour.BdvBehaviours.lambda$null$4(BdvBehaviours.java:81)
	at java.lang.Thread.run(Thread.java:748)
'''

**Comment by maximka48** [comment]
seems to be resolved after the update today. I propose to monitor it one more week.
